groups:
  - name: High Memory
    rules:
      - alert: high_memory_load
        expr: (node_memory_MemTotal_bytes - (node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes )) / node_memory_MemTotal_bytes * 100 > 90
        for: 1m
        labels:
          user: prometheus
          severity: warning
        annotations:
          summary: "High Memory usage detected"
          description: "{{$labels.instance}}: Memory usage is above 90% (current value is: {{ $value }}%)"
          username: "@tset"
