groups:
  - name: Node down
    rules:
      # Alert for any instance that is unreachable for >1 minutes.
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          user: prometheus
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."
          username: "@tset"
